name       : python-enum-compat
version    : 0.0.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/41/46/8ed2368976d934652d8f33f1fdd86f5580fab45e890c90a848e83097a093/enum-compat-0.0.3.tar.gz : 3677daabed56a6f724451d585662253d8fb4e5569845aafa8bb0da36b1a8751e
license    : MIT
component  : programming.python
summary    : enum/enum34 compatibility package
description: |
    This is a virtual package, its whole purpose is to install enum34 on Python older than 3.4.
builddeps  :
    - python-setuptools
build      : |
    %python_setup    
install    : |
    %python_install
